### ISSUE TITLE
DateTimeException Invalid Hijrah day of month: 30

### ISSUE THREAD

**Issue by mhelmi** [msarhan/ummalqura-calendar#31] opened 2021-07-10 06:13 UTC
Caused by com.github.msarhan.ummalqura.calendar.DateTimeException
Invalid Hijrah day of month: 30
com.github.msarhan.ummalqura.calendar.HijrahChronology.getEpochDay (HijrahChronology.java:255)
com.github.msarhan.ummalqura.calendar.HijrahChronology.toGregorian (HijrahChronology.java:697)
com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.set (UmmalquraCalendar.java:250)
com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.<init> (UmmalquraCalendar.java:193)
com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.<init> (UmmalquraCalendar.java:155)

this happened at (30/11/1442)

**Comment by bassil-altamimi** [comment] 2021-07-10 11:50
same issue

**Comment by mhelmi** [comment] 2021-07-11 12:09
To reproduce this bug change the mobile date to 30 Dhu'l-Qi'dah 1442 and set the default value from calendar

new UmmalquraCalendar(1500, UmmalquraCalendar.THUL_QIDAH, 30);

**Comment by msarhan** [comment] 2021-07-12 09:20
This is a duplicate of #26 which is solved in 2.0.2 version.

**Closed as completed by msarhan** 2021-07-12 09:20 UTC

**Comment by mhelmi** [comment] 2021-07-12 09:41
> This is a duplicate of #26 which is solved in 2.0.2 version.

Actually, it's not solved for me in 2.0.2 version.

**Comment by msarhan** [comment] 2021-07-12 09:52
I've run your sample code above and it it's working fine.

Please to check this test case and make changes to use 1442-11-30 to make sure it is working:
https://github.com/msarhan/ummalqura-calendar/blob/fc1c70bfbd29dc28638ae123bf2a02f3ff05230d/src/test/java/com/github/msarhan/ummalqura/calendar/HijrahChronologyTest.java#L100-L106

If you still get the same error, please to submit a test case to reproduce the issue.
