### ISSUE TITLE
 com.github.msarhan.ummalqura.calendar.DateTimeException: Invalid Hijrah day of month: 30

### ISSUE THREAD

**Issue by LPC351710** [msarhan/ummalqura-calendar#28] opened 2020-12-22 07:06 UTC
UmmalquraCalendar tempWorkingCalendar = new UmmalquraCalendar();
        tempWorkingCalendar.set(1442, 6, 30);
        String displayM = tempWorkingCalendar.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.ENGLISH)
                + " " + tempWorkingCalendar.get(Calendar.DAY_OF_MONTH) + ", " + tempWorkingCalendar.get(Calendar.MONTH) + ", " + month.getYear();

 com.github.msarhan.ummalqura.calendar.DateTimeException: Invalid Hijrah day of month: 30
        at com.github.msarhan.ummalqura.calendar.HijrahChronology.getEpochDay(HijrahChronology.java:255)
        at com.github.msarhan.ummalqura.calendar.HijrahChronology.toGregorian(HijrahChronology.java:697)
        at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.set(UmmalquraCalendar.java:250)
        at java.util.Calendar.set(Calendar.java:1227)

**Comment by LPC351710** [comment] 2020-12-22 07:08
It says Invalid Hijrah day of month: 30 but month 7 does have 30 days!

**Comment by LPC351710** [comment] 2020-12-22 08:55
I found the problem, in the hijrah-config.properties file
1442=29 30 29 30 29 30 29 30 30 29 30 29

**Comment by Sabboo** [comment] 2020-12-22 15:29
Related to #26

**Comment by msarhan** [comment] 2021-05-01 09:11
Duplicate of #26

**Closed by msarhan** 2021-05-01 09:11 UTC
Labels: duplicate
